# Generated by Django 2.2.6 on 2019-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word-net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordnet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
