# Generated by Django 2.2.6 on 2019-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word-net', '0002_wordnet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordnet',
            name='hypernyms',
            field=models.ManyToManyField(related_name='_wordnet_hypernyms_+', to='word-net.WordNet'),
        ),
        migrations.AddField(
            model_name='wordnet',
            name='hyponyms',
            field=models.ManyToManyField(related_name='_wordnet_hyponyms_+', to='word-net.WordNet'),
        ),
    ]
