# Generated by Django 2.2.6 on 2019-10-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word-net', '0003_auto_20191015_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordnet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordnet',
            name='hypernyms',
            field=models.ManyToManyField(blank=True, null=True, related_name='_wordnet_hypernyms_+', to='word-net.WordNet'),
        ),
        migrations.AlterField(
            model_name='wordnet',
            name='hyponyms',
            field=models.ManyToManyField(blank=True, null=True, related_name='_wordnet_hyponyms_+', to='word-net.WordNet'),
        ),
    ]
